### ISSUE TITLE
Global directive to Morph-Replace

### ISSUE THREAD

**Issue by amckinnis** [jofftiquez/vue-morphling#23]
It's not stated in the documentation, I was curious if you can do a global directive for Replace?  I have a large chuck of which needs multiple REGEX characters replaced - in a specific order (it's a three step process/loop).   

example below:

Hi there\,   \n\nArnie McKinnis is inviting you to a scheduled Zo
om meeting. \n\nJoin from PC\, Mac\, Linux\,   iOS or Android: https://zoom.u
s/j/996419469\n\nOr iPhone one-tap :\n    US: +16465588665\,\,996419469#  o
r +14086380986\,\,996419469# \nOr   Telephone:\n    Dial(for higher   quality\,
dial a number based on your current   location): \n        US: +1 646 558 86
65  or   +1 408 638 0986 \n    Meeting ID: 996   419 469\n    International num
bers available:   https://zoom.us/u/yRlMjYsT\n\n

**Comment by jofftiquez** [comment]
@amckinnis hello, you're right it's not a feature yet. But I can create one for you. Just kindly give me a sample input and expected out so I could formulate a logic for this feature, example: 

Input: 

`Foo bar baz`

Output: 

`bar bar bar`

**Comment by jofftiquez** [comment]
> I have a large chuck of which needs multiple REGEX characters replaced

In your example you mean the `\n`s?

**Comment by jofftiquez** [comment]
For a quick solution maybe you could use the `v-html` directive?

```
<p v-html="someParagraph"></p>
```

**Comment by jofftiquez** [comment]
@amckinnis closing this for now. Kindly re-open when more info are provided. Thanks.
